GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Budi",
    "email": "budi69@gmail.com"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Dhimas Satrio",
    "email": "dhimassatrio7@gmail.com"
}


###
DELETE http://localhost:5000/users/2